import BN from 'bn.js';
import type { JsonTransaction } from '../json';
export type TransactionTypeKey = 'SendTx' | 'ActivationTx' | 'InviteTx' | 'KillTx' | 'SubmitFlipTx' | 'SubmitAnswersHashTx' | 'SubmitShortAnswersTx' | 'SubmitLongAnswersTx' | 'EvidenceTx' | 'OnlineStatusTx' | 'KillInviteeTx' | 'ChangeGodAddressTx' | 'BurnTx' | 'ChangeProfileTx' | 'DeleteFlipTx' | 'DeployContractTx' | 'CallContractTx' | 'TerminateContractTx' | 'DelegateTx' | 'UndelegateTx' | 'KillDelegatorTx' | 'StoreToIpfsTx';
export type TransactionTypeValue = 0x0 | 0x1 | 0x2 | 0x3 | 0x4 | 0x5 | 0x6 | 0x7 | 0x8 | 0x9 | 0xa | 0xb | 0xc | 0xd | 0xe | 0xf | 0x10 | 0x11 | 0x12 | 0x13 | 0x14 | 0x15;
export declare const transactionType: Record<TransactionTypeKey, TransactionTypeValue>;
export declare class Transaction {
    private _nonce;
    private _epoch;
    private _type;
    private _to;
    private _amount;
    private _maxFee;
    private _tips;
    private _payload;
    private _signature;
    constructor(init?: Partial<{
        nonce: number;
        epoch: number;
        type: TransactionTypeValue;
        to: Uint8Array | string;
        amount: Uint8Array | string | number | BN;
        maxFee: Uint8Array | string | number | BN;
        tips: Uint8Array | string | number | BN;
        payload: Uint8Array | number[];
    }>);
    set nonce(nonce: number);
    get nonce(): number;
    set epoch(epoch: number);
    get epoch(): number;
    set type(type: TransactionTypeValue);
    get type(): number;
    set to(to: string | Uint8Array | null);
    get to(): string | null;
    set amount(amount: number | string | BN | Uint8Array | null);
    get amount(): BN | null;
    set maxFee(maxFee: number | string | BN | Uint8Array | null);
    get maxFee(): BN | null;
    set tips(tips: number | string | BN | Uint8Array | null);
    get tips(): BN | null;
    set payload(payload: Uint8Array | null);
    get payload(): Uint8Array | null;
    get signature(): Uint8Array | null;
    get hash(): string;
    get sender(): string | null;
    get gas(): number;
    static fromHex(hex: string): Transaction;
    static fromBytes(bytes: Uint8Array): Transaction;
    fromHex(hex: string): Transaction;
    fromBytes(bytes: Uint8Array): Transaction;
    fromJson(jsonTx: JsonTransaction): Transaction;
    toBytes(): Uint8Array;
    sign(key: string | Uint8Array | number[]): Transaction;
    toHex(withPrefix?: boolean): string;
    private _createProtoTxData;
}
//# sourceMappingURL=transaction.d.ts.map